name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pre-load simulator
      run: open -a Simulator.app --args -CurrentDeviceUDID <device id>
    - name: Build
      run: xcodebuild
    - name: Run tests
      run: xcodebuild test -project GitHubActionsUITest.xcodeproj -scheme GitHubActionsUITest
